import '@fontsource/noto-sans-jp/400.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';

import type { Metadata } from 'next';

import { BaseLayout } from '@/components/BaseLayout';
import { MuiThemeProvider } from '@/components/MuiThemeProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ja'>
      <body>
        <MuiThemeProvider>
          <BaseLayout>{children}</BaseLayout>
        </MuiThemeProvider>
      </body>
    </html>
  );
}
