version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../:/home/user/app
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - 3100:3100
